const Config = {
    FLOOR_SIZE: 20,
    WALL_HEIGHT: 15,
    ANTIALIAS: true,
    FOV: 75,
    SHADOWS: false,
    CAMERA_VERTICAL_ANGLE: Math.PI/6,
    CAMERA_DISTANCE: 8,
    TRUCK_VEL: 0.05,
    TRUCK_ROTATION_SPEED: 0.05,
    LIFTER_SPEED: 0.05,
    DISTANCE_TO_LIFT: 0.5
}